### ISSUE TITLE
In readme file

### ISSUE THREAD

**Issue by bhavanasisoundarya** [fssa-batch3/vignesh.ramachandran__web_project#27]
In read file it shows login as a admin in seller side But there no option to login as a admin or user in register page or login page.

```
Path:      /pages/products/menus/category?menu=1
Browser:   Chrome 112.0.0.0 on Windows 10
Viewport:  1504 x 892 @1.5x
Language:  en-GB
Cookies:   Enabled
```

[Open in BrowserStack](https://www.browserstack.com/user/try-live?url=https%3A%2F%2Fdeploy-preview-1--sr-catering.netlify.app%2Fpages%2Fproducts%2Fmenus%2Fcategory%3Fmenu%3D1&os=Windows&os_version=10&browser=Chrome&browser_version=112.0&resolution=1504x892&speed=1&start=true&ref=netlify-source)

Submitted from [Netlify Deploy Preview #1](https://deploy-preview-1--sr-catering.netlify.app/pages/products/menus/category?menu=1)

**Comment by SRVignesh2000** [comment]
Readme file for admin side is updated
