### ISSUE TITLE
password validation is missing

### ISSUE THREAD

**Issue by bhavanasisoundarya** [fssa-batch3/vignesh.ramachandran__web_project#28]
In register page password validation not validating properly.it accepts space also.

```
Path:      /pages/profile/login
Browser:   Chrome 112.0.0.0 on Windows 10
Viewport:  1017 x 892 @1.5x
Language:  en-GB
Cookies:   Enabled
```

[Open in BrowserStack](https://www.browserstack.com/user/try-live?url=https%3A%2F%2Fdeploy-preview-1--sr-catering.netlify.app%2Fpages%2Fprofile%2Flogin&os=Windows&os_version=10&browser=Chrome&browser_version=112.0&resolution=1017x892&speed=1&start=true&ref=netlify-source)

Submitted from [Netlify Deploy Preview #1](https://deploy-preview-1--sr-catering.netlify.app/pages/profile/login)

**Comment by SRVignesh2000** [comment]
Space also consider as a password. Eg: pass word
