### ISSUE TITLE
animation error

### ISSUE THREAD

**Issue by Thamimtommy** [fssa-batch3/vignesh.ramachandran__web_project#31]
### Description of issue
I find a bug in the home page after logging in. the cheif animation at the bottom of the page width was oversizing itself so the total page width is increasing. check it.

```
Path:      /index.html
Browser:   Chrome 112.0.0.0 on Windows 10
Viewport:  1504 x 892 @1.5x
Language:  en-GB
Cookies:   Enabled
```

[Open in BrowserStack](https://www.browserstack.com/user/try-live?url=https%3A%2F%2Fdeploy-preview-1--sr-catering.netlify.app%2Findex.html&os=Windows&os_version=10&browser=Chrome&browser_version=112.0&resolution=1504x892&speed=1&start=true&ref=netlify-source)

Submitted from [Netlify Deploy Preview #1](https://deploy-preview-1--sr-catering.netlify.app/index.html)

**Comment by SRVignesh2000** [comment]
Animation error fixed. Page width didn't extend.

**Comment by SRVignesh2000** [comment]
error fixed.
