### ISSUE TITLE
In edit profile

### ISSUE THREAD

**Issue by Thamimtommy** [fssa-batch3/vignesh.ramachandran__web_project#32]
### Description of issue

the edit profile page. the input accepts space in the name input field, same problem for the password also. The validation of the input was the error. try it. Thank you

```
Path:      /pages/profile/profile%20page
Browser:   Chrome 112.0.0.0 on Windows 10
Viewport:  1504 x 892 @1.5x
Language:  en-GB
Cookies:   Enabled
```

[Open in BrowserStack](https://www.browserstack.com/user/try-live?url=https%3A%2F%2Fdeploy-preview-1--sr-catering.netlify.app%2Fpages%2Fprofile%2Fprofile%2520page&os=Windows&os_version=10&browser=Chrome&browser_version=112.0&resolution=1504x892&speed=1&start=true&ref=netlify-source)

Submitted from [Netlify Deploy Preview #1](https://deploy-preview-1--sr-catering.netlify.app/pages/profile/profile%20page)

**Comment by SRVignesh2000** [comment]
Validation for name and password in profile page is fixed.

**Comment by SRVignesh2000** [comment]
issued fixed by using pattern
