### ISSUE TITLE
View dish error 

### ISSUE THREAD

**Issue by Thamimtommy** [fssa-batch3/vignesh.ramachandran__web_project#33]
### Description of issue
It only showing in the breakfast menu or category and not showing in other menu. example: I click high tea and I choose VIP but I couldn't in the dishes.
please check it.  

```
Path:      /pages/products/menus/category?menu=3
Browser:   Chrome 112.0.0.0 on Windows 10
Viewport:  1504 x 892 @1.5x
Language:  en-GB
Cookies:   Enabled
```

[Open in BrowserStack](https://www.browserstack.com/user/try-live?url=https%3A%2F%2Fdeploy-preview-1--sr-catering.netlify.app%2Fpages%2Fproducts%2Fmenus%2Fcategory%3Fmenu%3D3&os=Windows&os_version=10&browser=Chrome&browser_version=112.0&resolution=1504x892&speed=1&start=true&ref=netlify-source)

Submitted from [Netlify Deploy Preview #1](https://deploy-preview-1--sr-catering.netlify.app/pages/products/menus/category?menu=3)

**Comment by SRVignesh2000** [comment]
Breakfast menu only created. Other menu not created.

**Comment by SRVignesh2000** [comment]
All menu created
