### ISSUE TITLE
minor Issue SR

### ISSUE THREAD

**Issue by Thamimtommy** [fssa-batch3/vignesh.ramachandran__web_project#34]
### Description of issue
In add to cart page. The count in the header section above the my cart text. after I clicked the add to cart it is not increasing but after I refresh the page then only it changing it's count. Not a big problem but you have to look after it. Thank you.  

```
Path:      /pages/products/dishes/dish?menu=1&category=3
Browser:   Chrome 112.0.0.0 on Windows 10
Viewport:  1504 x 892 @1.5x
Language:  en-GB
Cookies:   Enabled
```

[Open in BrowserStack](https://www.browserstack.com/user/try-live?url=https%3A%2F%2Fdeploy-preview-1--sr-catering.netlify.app%2Fpages%2Fproducts%2Fdishes%2Fdish%3Fmenu%3D1%26category%3D3&os=Windows&os_version=10&browser=Chrome&browser_version=112.0&resolution=1504x892&speed=1&start=true&ref=netlify-source)

Submitted from [Netlify Deploy Preview #1](https://deploy-preview-1--sr-catering.netlify.app/pages/products/dishes/dish?menu=1&category=3)

**Comment by SRVignesh2000** [comment]
reload function added, when user press the Add to cart button.

**Comment by SRVignesh2000** [comment]
issue fixed by adding window.location.reload()
