### ISSUE TITLE
Same Dishes issue in view order dish.

### ISSUE THREAD

**Issue by Thamimtommy** [fssa-batch3/vignesh.ramachandran__web_project#36]
### Description of issue

In high tea their are no dishes and after I added to cart. I ordered it and view that order and not showing the item dishes. 

```
Path:      /pages/profile/my%20orders.html
Browser:   Chrome 112.0.0.0 on Windows 10
Viewport:  1504 x 892 @1.5x
Language:  en-GB
Cookies:   Enabled
```

[Open in BrowserStack](https://www.browserstack.com/user/try-live?url=https%3A%2F%2Fdeploy-preview-1--sr-catering.netlify.app%2Fpages%2Fprofile%2Fmy%2520orders.html&os=Windows&os_version=10&browser=Chrome&browser_version=112.0&resolution=1504x892&speed=1&start=true&ref=netlify-source)

Submitted from [Netlify Deploy Preview #1](https://deploy-preview-1--sr-catering.netlify.app/pages/profile/my%20orders.html)

**Comment by SRVignesh2000** [comment]
I only added dishes for Breakfast.

**Comment by SRVignesh2000** [comment]
Issue fixed by creating main.js

**Comment by SRVignesh2000** [comment]
bug fixed by creating main.js

**Comment by SRVignesh2000** [comment]
bug fixed.
