### ISSUE TITLE
validation in order page.

### ISSUE THREAD

**Issue by Thamimtommy** [fssa-batch3/vignesh.ramachandran__web_project#37]
### Description of issue.
The no of guest input validation error because it accepts crores of guest.

```
Path:      /pages/profile/my%20orders.html
Browser:   Chrome 112.0.0.0 on Windows 10
Viewport:  1504 x 892 @1.5x
Language:  en-GB
Cookies:   Enabled
```

[Open in BrowserStack](https://www.browserstack.com/user/try-live?url=https%3A%2F%2Fdeploy-preview-1--sr-catering.netlify.app%2Fpages%2Fprofile%2Fmy%2520orders.html&os=Windows&os_version=10&browser=Chrome&browser_version=112.0&resolution=1504x892&speed=1&start=true&ref=netlify-source)

Submitted from [Netlify Deploy Preview #1](https://deploy-preview-1--sr-catering.netlify.app/pages/profile/my%20orders.html)

**Comment by SRVignesh2000** [comment]
Bug fixed. It allows only 1500 or below 1500 guests.

**Comment by SRVignesh2000** [comment]
issue fixed by setting limit
